catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'
urlpatterns = [
    path("", views.index, name="index"),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path(
        'author/<int:pk>',
        views.AuthorDetailView.as_view(),
        name='author-detail'
    ),
    path(
        'mybooks/', 
        views.LoanedBooksByUserListView.as_view(), 
        name='my-borrowed'
    ),
    path(
        'borrowed/', 
        views.LoanedBooksAllListView.as_view(), 
        name='all-borrowed'
    ),
    path(
        'book/<uuid:pk>/renew/', 
        views.renew_book_librarian, 
        name='renew-book-librarian'
    ),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path(
        'author/<int:pk>/update/',
        views.AuthorUpdate.as_view(),
        name='author-update'
    ),
    path(
        'author/<int:pk>/delete/',
        views.AuthorDelete.as_view(),
        name='author-delete'
    ),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path(
        'book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'
    ),
    path(
        'book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'
    ),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
import uuid

from datetime import date
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(
        max_length=200, 
        help_text='Enter a book genre (e.g. Science Fiction)'
    )

    def __str__(self) -> str:
        return self.name
    
class Language(models.Model):
    """
    Model represening a Language (e.g. English, French, Japanese, etc.)
    """
    name = models.CharField(
        max_length=200, 
        help_text='Enter the book\'s natural language (e.g. English, French, Japanese etc.)'
    )

    def __str__(self) -> str:
        return self.name

class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can 
    # have multiple books.
    # Author is a string rather than an object because it hasn't been declared 
    # yet in the file.
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(
        max_length=1000, help_text='Enter a brief description of the book'
    )
    isbn = models.CharField(
        'ISBN', 
        max_length=13, 
        unique=True, 
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>'
    )

    # ManyToManyField used because genre can contain many books. Books can 
    # cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(
        Genre, help_text='Select a genre for this book'
    )
    language = models.ForeignKey(
        'Language', on_delete=models.SET_NULL, null=True
    )

    def display_genre(self):
        """
        Create a string for the Genre. This is required to display genre in 
        Admin.
        """
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

    class Meta:
        ordering = ['title', 'author']

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self) -> str:
        return reverse('catalog:book-detail', args=(self.id,))
    
class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed 
    from the library).
    """
    id = models.UUIDField(
        primary_key=True, 
        default=uuid.uuid4, 
        help_text='Unique ID for this particular book across whole library'
    )
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability'
    )

    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True
    )

    class Meta:
        ordering = ['due_back']
        permissions = [("can_mark_returned", "Set book as returned"),]

    def __str__(self) -> str:
        return f'{self.id} ({self.book.title})'
    
    @property
    def is_overdue(self):
        """
        Determines if the book is overdue based on due date and current date.
        """
        return bool(self.due_back and date.today() > self.due_back)

class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('catalog:author-detail', args=(self.id,))
    
    def __str__(self) -> str:
        return f'{self.last_name}, {self.first_name}'

catalog/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import BookInstance

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text="Enter a date between now and 4 weeks (default 3)."
    )

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        
        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead')
            )
        
        # Remember to always return the cleaned data.
        return data
    
class RenewBookModelModelForm(forms.ModelForm):
    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead')
            )

        # Remember to always return the cleaned data
        return data

    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('New renewal date')}
        help_texts = {
            'due_back': _('Enter a date between now and 4 weeks (default 3).')
        }

catalog/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin, \
                                       PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpRequest
from django.urls import reverse, reverse_lazy
from django.views import generic
from typing import Any

from .forms import RenewBookForm
from .models import Book, Author, BookInstance, Genre, Language

# Create your views here.
def index(request:HttpRequest):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = \
        BookInstance.objects.filter(status__exact='a').count()
    
    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    num_genres = Genre.objects.count()
    num_books_contain_the = Book.objects.filter(title__icontains='the').count()
    
    # Number of visites to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_genres': num_genres,
        'num_books_contain_the': num_books_contain_the,
        'num_visits': num_visits,
    }

    return render(request, 'catalog/index.html', context=context)

class BookListView(generic.ListView):
    model = Book
    paginate_by = 2

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view listing books on loan to current user.
    """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self) -> QuerySet[Any]:
        return (
            BookInstance.objects.filter(borrower=self.request.user)
                .filter(status__exact='o')
                .order_by('due_back')
        )
    
class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    """
    Generic class-based view listing all books on loan. Only visible to users 
    with can_mark_returned permission.
    """
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self) -> QuerySet[Any]:
        return (
            BookInstance.objects.filter(status__exact='o').order_by('due_back')
        )
    
@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request:HttpRequest, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request 
        # (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just 
            # write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('catalog:all-borrowed'))
        
    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + \
            datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)

class AuthorCreate(PermissionRequiredMixin, generic.edit.CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/06/2020'}
    permission_required = 'catalog.add_author'

class AuthorUpdate(PermissionRequiredMixin, generic.edit.UpdateView):
    model = Author

    # Not recommended (potential security issue if more fields added)
    fields = '__all__'

    permission_required = 'catalog.change_author'

class AuthorDelete(PermissionRequiredMixin, generic.edit.DeleteView):
    model = Author
    success_url = reverse_lazy('catalog:authors')

    permission_required = 'catalog.delete_author'

class BookCreate(PermissionRequiredMixin, generic.edit.CreateView):
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre', 'language']
    permission_required = 'catalog.add_book'

class BookUpdate(PermissionRequiredMixin, generic.edit.UpdateView):
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre', 'language']
    permission_required = 'catalog.change_book'

class BookDelete(PermissionRequiredMixin, generic.edit.DeleteView):
    model = Book
    success_url = reverse_lazy('catalog:books')
    permission_required = 'catalog.delete_book'

catalog/templates/catalog/author_confirm_delete.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Delete Author</h1>

    <p>Are you sure you want to delete the author: {{ author }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete." />
    </form>
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Author: {{ author }}</h1>
    <!-- Author detail link not defined yet -->
    <p>
        {{ author.date_of_birth }} -
        {% if author.date_of_death %}
            {{ author.date_of_death }}
        {% endif %}
    </p>

    <div style="margin-left: 20px; margin-top: 20px;">
        <h4>Books</h4>

        <dl>
            {% for book in author.book_set.all %}
                <dt>
                    <a href="{{ book.get_absolute_url }}">{{ book }}</a>
                    ({{ book.bookinstance_set.all.count }})
                </dt>
                <dd>{{ book.summary }}</dd>
            {% endfor %}
        </dl>
    </div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Author List</h1>
    {% if author_list %}
        <ul>
            {% for author in author_list %}
                <li>
                    <a href="{{ author.get_absolute_url }}">
                        {{ author }} ({{ author.date_of_birth }} -
                        {% if author.date_of_death %}
                            {{ author.date_of_death }}
                        {% endif %}
                        )
                    </a> 
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no authors available.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block title %}
            <title>Local Library</title>
        {% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link 
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"
        >
        <!-- Add additional CSS in static file -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'catalog/css/styles.css' %}">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {% block sidebar %}
                        <ul class="sidebar-nav">
                            <li>
                                <a href="{% url 'catalog:index' %}">Home</a>
                            </li>
                            <li>
                                <a href="{% url 'catalog:books' %}">
                                    All books
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'catalog:authors' %}">
                                    All authors
                                </a>
                            </li>
                        </ul>
                        <ul class="sidebar-nav">
                            {% if user.is_authenticated %}
                                <li>User: {{ user.get_username }}</li>
                                <li>
                                    <a href="{% url 'catalog:my-borrowed' %}">
                                        My Borrowed
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'logout' %}?next={{ request.path }}">
                                        Logout
                                    </a>
                                </li>
                            {% else %}
                                <li>
                                    <a href="{% url 'login' %}?next={{ request.path }}">
                                        Login
                                    </a>
                                </li>
                            {% endif %}
                        </ul>

                        {% if perms.catalog.can_mark_returned %}
                            <hr>
                            <ul class="sidebar-nav">
                                <li>Staff</li>
                                <li>
                                    <a href="{% url 'catalog:all-borrowed' %}">
                                        All borrowed
                                    </a>
                                </li>
                            </ul>
                        {% endif %}
                    {% endblock %}
                </div>
                <div class="col-sm-10">
                    {% block content %}{% endblock %}
                    {% block pagination %}
                        {% if is_paginated %}
                            <div class="pagination">
                                <span class="page-links">
                                    {% if page_obj.has_previous %}
                                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">
                                            previous
                                        </a>
                                    {% endif %}
                                    <span class="page-current">
                                        Page {{ page_obj.number }} of 
                                        {{ page_obj.paginator.num_pages }}.
                                    </span>
                                    {% if page_obj.has_next %}
                                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">
                                            next
                                        </a>
                                    {% endif %}
                                </span>
                            </div>
                        {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

catalog/templates/catalog/book_confirm_delete.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Delete Author</h1>

    <p>Are you sure you want to delete the book: {{ book }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete." />
    </form>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>
    <p>
        <strong>Author:</strong> 
        <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a>
    </p>
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

    <div style="margin-left: 20px; margin-top: 20px;">
        <h4>Copies</h4>

        {% for copy in book.bookinstance_set.all %}
            <hr>
            <p 
                class="{% if copy.status == 'a' %} text-success {% elif copy.status == 'm' %} text-danger {% else %} text-warning {% endif %}"
            >
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != 'a' %}
                <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
            {% endif %}
            <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> 
                    ({{ book.author }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Renew: {{ book_instance.book.title }}</h1>
    <p>Borrower: {{ book_instance.borrower }}</p>
    <p {% if book_instance.is_overdue %} class="text-danger" {% endif %}>
        Due date: {{ book_instance.due_back }}
    </p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>All Borrowed books</h1>

    {% if bookinstance_list %}
        <ul>
            {% for bookinst in bookinstance_list %}
                <li class="{% if bookinst.is_overdue %} text-danger {% endif %}">
                    <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">
                        {{ bookinst.book.title }}
                    </a>
                    ({{ bookinst.due_back }}) - {{ bookinst.borrower }}
                    {% if perms.catalog.can_mark_returned %}
                    -
                    <a href="{% url 'catalog:renew-book-librarian' bookinst.id %}">
                        Renew
                    </a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
        <ul>
            {% for bookinst in bookinstance_list %}
                <li class="{% if bookinst.is_overdue %} text-danger {% endif %}">
                    <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">
                        {{ bookinst.book.title }}
                    </a>
                    ({{ bookinst.due_back }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base_generic.html" %}

{% block title %}
    <title>Local Library Home</title>
{% endblock %}

{% block content %}
    <h1>Local Library Home</h1>
    <p>
        Welcome to LocalLibrary, a website developed by
        <em>Mozilla Developer Network</em>!
    </p>
    <h2>Dynamic content</h2>
    <p>The library has the following record counts:</p>
    <ul>
        <li><strong>Books:</strong> {{ num_books }}</li>
        <li><strong>Copies:</strong> {{ num_instances }}</li>
        <li>
            <strong>Copies available:</strong> {{ num_instances_available }}
        </li>
        <li><strong>Authors:</strong> {{ num_authors }}</li>
        <li><strong>Genres:</strong>  {{ num_genres }}</li>
        <li>
            <strong>Books contain "The" Word:</strong> 
            {{ num_books_contain_the }}
        </li>
    </ul>

    <p>
        You have visited this page {{ num_visits }} 
        time{{ num_visits|pluralize }}.
    </p>
{% endblock %}